services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_INITDB_SKIP_TZINFO: 'yes'
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u${MYSQL_USER} -p${MYSQL_PASSWORD}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/home/java/app
    ports:
      - ${PORT:-8080}:8080
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
    driver: local